"""Create app_users table

Revision ID: 062c3d2fb600
Revises: ace6a879cee4
Create Date: 2024-06-08 19:43:26.625951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062c3d2fb600'
down_revision = 'ace6a879cee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('whatsapp_notification_enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint("email LIKE '%%@%%.%%'"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_users')
    # ### end Alembic commands ###
