"""Initial migration

Revision ID: 0be1c60a6e87
Revises: 905477e8f8bb
Create Date: 2024-06-08 15:47:13.118497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be1c60a6e87'
down_revision = '905477e8f8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=256), nullable=False))
    op.add_column('user', sa.Column('mobile', sa.Numeric(precision=10), nullable=False))
    op.create_unique_constraint(None, 'user', ['mobile'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'mobile')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
