"""Create app_users table

Revision ID: 37f25e7a7ed5
Revises: 92d1b3786df7
Create Date: 2024-06-08 21:00:45.659257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f25e7a7ed5'
down_revision = '92d1b3786df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('whatsapp_notification_enable', sa.Boolean(), nullable=False),
    sa.CheckConstraint("email LIKE '%%@%%.%%'"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_users')
    # ### end Alembic commands ###
